"""Add summary to threads

Revision ID: f24d9ab743bc
Revises: 22b398399428
Create Date: 2026-06-12 13:47:52.981262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24d9ab743bc'
down_revision: Union[str, None] = '22b398399428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'summary')
    # ### end Alembic commands ###
